/* 0.5.4 2021-04-23 21:06:13 */
var app = new function() {
    this.name = "Pushing Life Grandfusion", this.version = "1", this.date = "2025", this.folder = "asset-v1/", this.looptime = 8000, this.bpm = 120, this.totalframe = 384, this.nbpolo = 10, this.nbloopbonus = 2, this.bonusloopA = !0, this.bonusendloopA = !0, this.recmaxloop = 96, this.recminloop = 4, this.recmintime = Math.round(this.looptime / 1e3) * this.recminloop, this.spritepolo = "polo-sprite.png", this.spritepicto = "game-picto.png", this.colBck = "#0f1521", this.col0 = "#828da0", this.col1 = "#596988", this.col2 = "#384863", this.col3 = "#202a3c", this.col4 = "#131a2a", this.animearray = [{
        name: "01kick",
        color: "af8553",
        uniqsnd: !1
    }, {
        name: "02snare",
        color: "af8553",
        uniqsnd: !1
    }, {
        name: "03clic",
        color: "af8553",
        uniqsnd: !1
    }, {
        name: "04klop",
        color: "af8553",
        uniqsnd: !0
    }, {
        name: "05tombreak",
        color: "af8553",
        uniqsnd: !1
    }, {
        name: "06bass",
        color: "10a3b7",
        uniqsnd: !1
    }, {
        name: "07mmmhah",
        color: "10a3b7",
        uniqsnd: !0
    }, {
        name: "08tututoung",
        color: "10a3b7",
        uniqsnd: !1
    }, {
        name: "09boowop",
        color: "10a3b7",
        uniqsnd: !0
    }, {
        name: "10woah",
        color: "10a3b7",
        uniqsnd: !1
    }, {
        name: "11nugununugu",
        color: "fe0849",
        uniqsnd: !1
    }, {
        name: "12string",
        color: "fe0849",
        uniqsnd: !1
    }, {
        name: "13lowarp",
        color: "fe0849",
        uniqsnd: !1
    }, {
        name: "14settoarp",
        color: "fe0849",
        uniqsnd: !1
    }, {
        name: "15duuduuduu",
        color: "fe0849",
        uniqsnd: !0
    }, {
        name: "16somuch",
        color: "9573fe",
        uniqsnd: !1
    }, {
        name: "17casting",
        color: "9573fe",
        uniqsnd: !1
    }, {
        name: "18ahwoo",
        color: "9573fe",
        uniqsnd: !1
    }, {
        name: "19lastday",
        color: "9573fe",
        uniqsnd: !1
    }, {
        name: "20mind",
        color: "9573fe",
        uniqsnd: !1
    }, {
        name: "1_tshkuh",
        color: "18373d",
        uniqsnd: !0
    }, {
        name: "2_kick",
        color: "18373d",
        uniqsnd: !0
    }, {
        name: "3_kahp",
        color: "18373d",
        uniqsnd: !0
    }, {
        name: "4_pshtom",
        color: "18373d",
        uniqsnd: !0
    }, {
        name: "5_clics",
        color: "18373d",
        uniqsnd: !0
    }, {
        name: "6_ooh",
        color: "2e266d",
        uniqsnd: !0
    }, {
        name: "7_boomboom",
        color: "2e266d",
        uniqsnd: !0
    }, {
        name: "8_daft",
        color: "2e266d",
        uniqsnd: !0
    }, {
        name: "9_tukatadrop",
        color: "2e266d",
        uniqsnd: !0
    }, {
        name: "10_longuebass",
        color: "2e266d",
        uniqsnd: !0
    }, {
        name: "11_toungtu",
        color: "9a1e25",
        uniqsnd: !0
    }, {
        name: "12_tutuarp",
        color: "9a1e25",
        uniqsnd: !0
    }, {
        name: "13_hmmpad",
        color: "9a1e25",
        uniqsnd: !0
    }, {
        name: "14_ploum",
        color: "9a1e25",
        uniqsnd: !0
    }, {
        name: "15_siffle",
        color: "9a1e25",
        uniqsnd: !1
    }, {
        name: "16_weywe",
        color: "191a26",
        uniqsnd: !0
    }, {
        name: "17_lilcrush",
        color: "191a26",
        uniqsnd: !0
    }, {
        name: "18_etienne",
        color: "191a26",
        uniqsnd: !0
    }, {
        name: "19_readygo",
        color: "191a26",
        uniqsnd: !1
    }, {
        name: "20_woah",
        color: "191a26",
        uniqsnd: !0
    }], this.bonusarray = [];
    for (var n = 0, o = this.animearray.length; n < o; n++) {
        var a = this.animearray[n].name;
        this.animearray[n].soundA = a + "_a", this.animearray[n].soundB = this.animearray[n].uniqsnd ? a + "_a" : a + "_b", this.animearray[n].anime = a + "-sprite.png", this.animearray[n].animeData = a + ".json"
    }
};
